name: Build, Push DataStream Singularity Containers on X86
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to build from (leave empty to use current branch)'
        required: false
        default: ''
        type: string
      force_build_deps:
        description: 'Force build datastream-deps (provide tag version, e.g., 1.0.0)'
        required: false
        default: ''
        type: string
      force_build_ds:
        description: 'Force build datastream (provide tag version, e.g., 1.0.0)'
        required: false
        default: ''
        type: string
  push:
    branches:
      - main
      - Datastream_Workflows

    paths:
      - 'versions.yml'

permissions:
  contents: read
  security-events: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      build_deps: ${{ steps.changes.outputs.build_deps }}
      build_ds: ${{ steps.changes.outputs.build_ds }}
      deps_version: ${{ steps.changes.outputs.deps_version }}
      ds_version: ${{ steps.changes.outputs.ds_version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Install singularity with apt-get
      run: |
        # sudo apt-get update && sudo apt-get install -y \
        # build-essential \
        # libssl-dev \
        # uuid-dev \
        # libgpgme11-dev \
        # squashfs-tools \
        # libseccomp-dev \
        # pkg-config
        
        sudo apt-get install -y singularity-container
        singularity --version
    - name: Build singularity image file
      run: |
        pwd
        cd singularity
        sudo singularity build datastream.sif datastream.def
      
      
      
    - name: run datastream.sif with singularity 
      run: |
        singularity exec singularity/datastream.sif python3 -c "import datastreamcli; print('OK')"
        
    - name: run datastream help
      run: |
       singularity exec singularity/datastream.sif /datastreamcli/scripts/datastream --help
       # # singularity exec singularity/datastream.sif /datastreamcli/scripts/datastream -s 202006200100 \
       #              -e 202006210000 \
       #              -C NWM_RETRO_V3 \
       #              -d ./data/datastream_test_1 \
       #              -g https://ciroh-community-ngen-datastream.s3.us-east-1.amazonaws.com/resources/v2.2_hydrofabric/datastream-resources/VPU_09/config/nextgen_VPU_09.gpkg \
       #              -R ./configs/ngen/realization_sloth_nom_cfe_pet_troute.json \
       #              -n 4
      

    

         
